<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\ReviewCardViewModel\**" />
    <Compile Remove="Views\ReviewCreateInputVM\**" />
    <Content Remove="Views\ReviewCardViewModel\**" />
    <Content Remove="Views\ReviewCreateInputVM\**" />
    <EmbeddedResource Remove="Views\ReviewCardViewModel\**" />
    <EmbeddedResource Remove="Views\ReviewCreateInputVM\**" />
    <None Remove="Views\ReviewCardViewModel\**" />
    <None Remove="Views\ReviewCreateInputVM\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\CheckinModels\" />
    <Folder Include="Models\MemberModels\" />
    <Folder Include="Models\OperationModels\" />
    <Folder Include="Models\ReservationModels\" />
    <Folder Include="Models\VenueModels\" />
    <Folder Include="ViewModels\MemberViewModels\" />
    <Folder Include="ViewModels\CheckinViewModels\" />
    <Folder Include="ViewModels\VenueViewModels\" />
    <Folder Include="ViewModels\ReservationViewModels\" />
    <Folder Include="Views\Reservation\" />
    <Folder Include="wwwroot\images\icons\" />
    <Folder Include="wwwroot\images\logo\" />
    <Folder Include="wwwroot\images\venues\" />
    <Folder Include="wwwroot\uploads\" />
  </ItemGroup>

</Project>
